linters:
  enable-all: true
  disable:
    - varnamelen
    - funlen
    - cyclop
    - gocyclo
    - paralleltest
    - gochecknoglobals
    - wsl
    - goerr113
    - gocognit
    - dupl

issues:
  fix: true
