# https://taskfile.dev

version: '3'

vars:
  GREETING: Hi!
  EXECUTABLE_NAME: vault
  DOCKER_IMAGE_NAME: vault
  VAULT_DIR: $HOME/.vault
  DOCKER_MOUNT_PATH: /root/.vault

tasks:
  fmt:
    cmds:
      - go fmt ./...
      - gofumpt -e -l -w -extra .

  lint:
    cmds:
      - golangci-lint run --sort-results

  dockerbuild:
    cmds:
      - docker build -t {{.DOCKER_IMAGE_NAME}} .

  dockerrun:
    cmds:
      - docker run -v {{.VAULT_DIR}}:{{.DOCKER_MOUNT_PATH}} -it {{.DOCKER_IMAGE_NAME}} {{.CLI_ARGS}}

  coverprofile:
    cmds:
      - mkdir -p coverage
      - go test -cover -coverprofile=coverage/cover.out ./...

  showcoverage:
    cmds:
      - go tool cover -html coverage/cover.out

  docs:
    cmds:
      - go run golang.org/x/pkgsite/cmd/pkgsite@latest

  build:
    cmds:
      - go generate ./...
      - mkdir -p bin
      - rm -rf bin/*
      - GOOS=linux GOARCH=amd64 go build -o bin/{{.EXECUTABLE_NAME}}-linux cmd/vault/*.go
      - GOOS=windows GOARCH=amd64 go build -o bin/{{.EXECUTABLE_NAME}}-windows cmd/vault/*.go
      - GOOS=darwin GOARCH=amd64 go build -o bin/{{.EXECUTABLE_NAME}}-darwin cmd/vault/*.go
      - zip -r -j bin/vault.zip bin/*

  buildrun:
    cmds:
      - ./bin/{{.EXECUTABLE_NAME}}-$(go env GOOS) {{.CLI_ARGS}}

  run:
    cmds:
      - go generate ./...
      - go run cmd/vault/*.go {{.CLI_ARGS}}

  test:
    cmds:
      - go test ./...

  clean:
    cmds:
      - rm -rf bin/*

  upgrade:
    cmds:
      - go get -u ./...
      - go mod tidy

  installdeps:
    cmds:
      - go mod tidy

  default:
    silent: true
    cmds:
      - echo "{{.GREETING}}, no task is provided to execute."
