# https://taskfile.dev

version: '3'

vars:
  GREETING: Hi!

tasks:
  fmt:
    cmds:
      - go fmt ./...
      - gofumpt -e -l -w -extra .

  lint:
    cmds:
      - staticcheck -checks all ./...
      - golangci-lint run

  coverage:
    cmds:
      - go test -cover -coverprofile=coverage/cover.out ./...

  showcoverage:
    cmds:
      - go tool cover -html coverage/cover.out

  vault-help:
    cmds:
      - go run cmd/vault/* -help

  docs:
    cmds:
      - go run golang.org/x/pkgsite/cmd/pkgsite@latest

  build:
    cmds:
      - go generate
      - go build -o bin/vault cmd/vault/*

  run:
    cmds:
      - go generate
      - go run cmd/vault/* {{.CLI_ARGS}}

  test:
    cmds:
      - go test ./...

  default:
    silent: true
    cmds:
      - echo "{{.GREETING}}, no task is provided to execute."
