# https://taskfile.dev

version: '3'

vars:
  GREETING: Hi!
  EXECUTABLE_NAME: vault

tasks:
  fmt:
    cmds:
      - go fmt ./...
      - gofumpt -e -l -w -extra .

  dockerbuild:
    cmds:
      - sudo docker build -t vault .

  dockerrun:
    cmds:
      - sudo docker run -it vault {{.CLI_ARGS}}

  lint:
    cmds:
      - staticcheck -checks all ./...
      - golangci-lint run

  coverprofile:
    cmds:
      - go test -cover -coverprofile=coverage/cover.out ./...

  showcoverage:
    cmds:
      - go tool cover -html coverage/cover.out

  vault-help:
    cmds:
      - go run cmd/vault/* -help

  docs:
    cmds:
      - go run golang.org/x/pkgsite/cmd/pkgsite@latest

  build:
    cmds:
      - go generate
      - GOOS=linux GOARCH=amd64 go build -o bin/{{.EXECUTABLE_NAME}} cmd/vault/*

  buildrun:
    cmds:
      - ./bin/{{.EXECUTABLE_NAME}} {{.CLI_ARGS}}

  run:
    cmds:
      - go generate
      - go run cmd/vault/* {{.CLI_ARGS}}

  test:
    cmds:
      - go test ./...

  default:
    silent: true
    cmds:
      - echo "{{.GREETING}}, no task is provided to execute."
